const INTERVAL_5_MINUTES = '5min';
const INTERVAL_15_MINUTES = '15min';
const INTERVAL_30_MINUTES = '30min';
const INTERVAL_60_MINUTES = '60min';
const INTERVAL_DAILY = '1d';
const HIGH_KEY = '2. high';
const LOW_KEY = '3. low';
const CLOSE_KEY = '4. close';
const TIME_SERIES_INTRADAY = 'TIME_SERIES_INTRADAY';
const TIME_SERIES_5_MINUTES = 'Time Series (5min)';
const TIME_SERIES_15_MINUTES = 'Time Series (15min)';
const TIME_SERIES_30_MINUTES = 'Time Series (30min)';
const TIME_SERIES_60_MINUTES = 'Time Series (60min)';
const TIME_SERIES_DAILY = 'TIME_SERIES_DAILY';
const TIME_SERIES_DAILY_KEY = 'Time Series (Daily)';

module.exports = {
  INTERVAL_5_MINUTES,
  INTERVAL_15_MINUTES,
  INTERVAL_30_MINUTES,
  INTERVAL_60_MINUTES,
  INTERVAL_DAILY,
  HIGH_KEY,
  LOW_KEY,
  CLOSE_KEY,
  TIME_SERIES_INTRADAY,
  TIME_SERIES_5_MINUTES,
  TIME_SERIES_15_MINUTES,
  TIME_SERIES_30_MINUTES,
  TIME_SERIES_60_MINUTES,
  TIME_SERIES_DAILY,
  TIME_SERIES_DAILY_KEY,
};
