const INTERVAL_1_MINUTE = '1min';
const TIME_SERIES_INTRADAY = 'TIME_SERIES_INTRADAY';
const TIME_SERIES_1_MINUTE = 'Time Series (1min)'
const TIME_SERIES_DAILY = 'TIME_SERIES_DAILY';
const TIME_SERIES_WEEKLY = 'TIME_SERIES_WEEKLY';
const TIME_SERIES_MONTHLY = 'TIME_SERIES_MONTHLY';

module.exports = {
  INTERVAL_1_MINUTE,
  TIME_SERIES_INTRADAY,
  TIME_SERIES_1_MINUTE,
  TIME_SERIES_DAILY,
  TIME_SERIES_WEEKLY,
  TIME_SERIES_MONTHLY,
};
